### ISSUE TITLE
Add items from Collections Sprint 2023

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#247]
```[tasklist]
### Tasks
- [ ] #263
- [ ] https://github.com/geobtaa/metadata/issues/288
- [ ] https://github.com/geobtaa/metadata/issues/290
- [ ] https://github.com/geobtaa/metadata/issues/349
- [ ] https://github.com/geobtaa/metadata/issues/409
- [ ] https://github.com/geobtaa/metadata/issues/410
- [ ] https://github.com/geobtaa/metadata/issues/411
- [ ] https://github.com/geobtaa/metadata/issues/412
```

**Comment by karenmajewicz** [comment]
https://docs.google.com/spreadsheets/d/1qBL6RSnF5wTh1hJmhVrMaviwkFFKfYtlrA_H5hrRfWg/edit?usp=sharing
