### ISSUE TITLE
ArcGIS Hubs

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#259]
```[tasklist]
### Tasks
- [ ] https://github.com/geobtaa/arcgis-hubs/issues/20							
- [ ] https://github.com/geobtaa/metadata/issues/187							
- [ ] https://github.com/geobtaa/metadata/issues/244							
- [ ] https://github.com/geobtaa/metadata/issues/249							
- [ ] https://github.com/geobtaa/metadata/issues/251							
- [ ] https://github.com/geobtaa/metadata/issues/268							
- [ ] https://github.com/geobtaa/metadata/issues/282							
- [ ] https://github.com/geobtaa/metadata/issues/283							
- [ ] https://github.com/geobtaa/metadata/issues/289							
- [ ] https://github.com/geobtaa/metadata/issues/299							
- [ ] https://github.com/geobtaa/metadata/issues/307							
- [ ] https://github.com/geobtaa/metadata/issues/311							
- [ ] https://github.com/geobtaa/metadata/issues/327							
- [ ] https://github.com/geobtaa/metadata/issues/329							
- [ ] https://github.com/geobtaa/metadata/issues/331							
- [ ] https://github.com/geobtaa/metadata/issues/345							
- [ ] https://github.com/geobtaa/metadata/issues/351							
- [ ] https://github.com/geobtaa/metadata/issues/359							
- [ ] https://github.com/geobtaa/metadata/issues/367							
- [ ] https://github.com/geobtaa/metadata/issues/373							
- [ ] https://github.com/geobtaa/metadata/issues/377							
- [ ] https://github.com/geobtaa/metadata/issues/381							
- [ ] https://github.com/geobtaa/metadata/issues/397							
- [ ] https://github.com/geobtaa/metadata/issues/405							
- [ ] https://github.com/geobtaa/metadata/issues/413							
- [ ] https://github.com/geobtaa/metadata/issues/415							
- [ ] https://github.com/geobtaa/metadata/issues/425							
- [ ] https://github.com/geobtaa/metadata/issues/475							
- [ ] https://github.com/geobtaa/metadata/issues/478							
- [ ] https://github.com/geobtaa/metadata/issues/479							
- [ ] https://github.com/geobtaa/metadata/issues/484							
- [ ] https://github.com/geobtaa/metadata/issues/485							
- [ ] https://github.com/geobtaa/metadata/issues/492							
- [ ] https://github.com/geobtaa/metadata/issues/498							
- [ ] https://github.com/geobtaa/metadata/issues/505							
- [ ] https://github.com/geobtaa/metadata/issues/513							
- [ ] https://github.com/geobtaa/metadata/issues/520							
- [ ] https://github.com/geobtaa/metadata/issues/523							
- [ ] https://github.com/geobtaa/metadata/issues/529							
- [ ] https://github.com/geobtaa/metadata/issues/540							
- [ ] https://github.com/geobtaa/metadata/issues/544							
- [ ] https://github.com/geobtaa/metadata/issues/549							
- [ ] https://github.com/geobtaa/metadata/issues/551							
- [ ] https://github.com/geobtaa/metadata/issues/562							
- [ ] https://github.com/geobtaa/metadata/issues/565							
- [ ] https://github.com/geobtaa/metadata/issues/568							
- [ ] https://github.com/geobtaa/metadata/issues/572							
- [ ] https://github.com/geobtaa/metadata/issues/581							
- [ ] https://github.com/geobtaa/metadata/issues/588							
- [ ] https://github.com/geobtaa/metadata/issues/608							
- [ ] https://github.com/geobtaa/metadata/issues/611							
- [ ] https://github.com/geobtaa/metadata/issues/649							
- [ ] https://github.com/geobtaa/metadata/issues/653							
- [ ] https://github.com/geobtaa/metadata/issues/654							
- [ ] https://github.com/geobtaa/metadata/issues/656							
- [ ] https://github.com/geobtaa/metadata/issues/658							
- [ ] https://github.com/geobtaa/metadata/issues/660							
- [ ] https://github.com/geobtaa/metadata/issues/661							
- [ ] https://github.com/geobtaa/metadata/issues/663							
- [ ] https://github.com/geobtaa/metadata/issues/665							
- [ ] https://github.com/geobtaa/metadata/issues/670							
- [ ] https://github.com/geobtaa/metadata/issues/671							
- [ ] https://github.com/geobtaa/metadata/issues/672							
- [ ] https://github.com/geobtaa/metadata/issues/675							
- [ ] https://github.com/geobtaa/metadata/issues/677							
- [ ] https://github.com/geobtaa/metadata/issues/684							
- [ ] https://github.com/geobtaa/metadata/issues/689							
- [ ] https://github.com/geobtaa/metadata/issues/698							
- [ ] https://github.com/geobtaa/metadata/issues/702							
- [ ] https://github.com/geobtaa/metadata/issues/706							
- [ ] https://github.com/geobtaa/metadata/issues/708							
- [ ] https://github.com/geobtaa/metadata/issues/712							
- [ ] https://github.com/geobtaa/metadata/issues/715							
- [ ] https://github.com/geobtaa/metadata/issues/725							
- [ ] https://github.com/geobtaa/metadata/issues/727							
- [ ] https://github.com/geobtaa/metadata/issues/728							
- [ ] https://github.com/geobtaa/metadata/issues/730							
- [ ] https://github.com/geobtaa/metadata/issues/735							
- [ ] https://github.com/geobtaa/metadata/issues/736							
- [ ] https://github.com/geobtaa/metadata/issues/737							
- [ ] https://github.com/geobtaa/metadata/issues/740
```
