### ISSUE TITLE
08a-01

### ISSUE THREAD

**Issue by karenmajewicz** [geobtaa/metadata#378]
### Tasks
- [ ] https://github.com/geobtaa/metadata/issues/67
- [ ] https://github.com/geobtaa/metadata/issues/24
- [ ] https://github.com/geobtaa/metadata/issues/350
- [ ] https://github.com/geobtaa/metadata/issues/363
- [ ] https://github.com/geobtaa/metadata/pull/347
- [ ] https://github.com/geobtaa/metadata/issues/303
- [ ] https://github.com/geobtaa/metadata/issues/196
- [ ] https://github.com/geobtaa/metadata/issues/132
- [ ] https://github.com/geobtaa/metadata/pull/346
- [ ] https://github.com/geobtaa/metadata/issues/380
- [ ] https://github.com/geobtaa/metadata/issues/401
- [ ] https://github.com/geobtaa/metadata/issues/402
- [ ] https://github.com/geobtaa/metadata/issues/382
- [ ] https://github.com/geobtaa/metadata/issues/579
- [ ] https://github.com/geobtaa/metadata/issues/580
- [ ] https://github.com/geobtaa/metadata/issues/637
- [ ] https://github.com/geobtaa/metadata/issues/722
- [ ] https://github.com/geobtaa/metadata/issues/741
- [ ] https://github.com/geobtaa/metadata/issues/745
